### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MrG0ldenFox** [dragon-forge/ExpandedEquivalence#1]
After installing latest version of Expanded Equivalence any old and new SP worlds will be stuck on loading making modpack unplayable, issue persists after mod deletion.

**Comment by Zeitheron** [comment]
Can't do anything without more context (version, logs etc)

**Comment by MrG0ldenFox** [comment]
[2023-01-22-4.log.gz](https://github.com/dragon-forge/ExpandedEquivalence/files/10474312/2023-01-22-4.log.gz)

This one should contain the correct Log. I did some testing, deleting mods, config files etc. it happens to be integration with equivalent energistics, maybe it has also other conflicts with other mods.

Also sorry for not attaching log in first place i tend to forget about it.

**Comment by Zeitheron** [comment]
Please do not report 1.12.2 here, it is no longer in development.

This does not seem to have anything to do with Expanded Equivalence, the issue seems to happen within the EquivalentEnergistics itself.
I remember ProjectE upgrading it's EMC values from 32-bit integer to 64-bits, thus changing method signature from `I` to `J`
This seems to be the cause of your issue, as seen here:

```
java.lang.AbstractMethodError: Method com/mordenkainen/equivalentenergistics/items/ItemEMCCell.getStoredEmc(Lnet/minecraft/item/ItemStack;)J is abstract
	at com.mordenkainen.equivalentenergistics.items.ItemEMCCell.getStoredEmc(ItemEMCCell.java) ~[ItemEMCCell.class:?]
	at moze_intel.projecte.utils.EMCHelper.getStoredEMCBonus(EMCHelper.java:327) ~[EMCHelper.class:?]
	at moze_intel.projecte.utils.EMCHelper.getEmcValue(EMCHelper.java:250) ~[EMCHelper.class:?]
	at moze_intel.projecte.events.ToolTipEvent.tTipEvent(ToolTipEvent.java:75) ~[ToolTipEvent.class:?]
```

Please check if you're running the latest version of it. If so, and the issue persists, try contacting them and reporting this issue.
Although I doubt that they still work on 1.12.2 at this point.
